name = "grad_minui"
modname = "grad_minui"
prefix = "grad_minui"
author = "DerZade"
files = [
    "mod.cpp",
    "Adler.paa",
    "LICENSE",
    "README.md"
]

key_name = "{{prefix}}-{{version}}"
sig_name = "{{prefix}}-{{version}}"

releasebuild = [
    "@zip"
]

[header_exts]
version= "{{git \"id 8\"}}"